### ISSUE TITLE
Reveal run id after before run

### ISSUE THREAD

**Issue by ewoelfel** [otto-de/jlineup#13]
It would be great to retrieve the 'before' run id after requesting the /runs endpoint either via body response or redirect in order to get the url to request for the 'after' phase

**Comment by MediaMarco** [comment]
You already get a location header when POSTing the config to start the 'before' run in the response headers like this:

`location: /runs/ebafb09d-14c1-4763-aeac-bf7507eee7b3`

Did you know that? 

Which id should `/runs` expose when there are multiple jobs that finished the 'before' stage?

**Comment by ewoelfel** [comment]
Thx for merging it!
