### ISSUE TITLE
after step does not recognice existing before step when running with delay

### ISSUE THREAD

**Issue by florianbrinkmann** [otto-de/jlineup#171]
Hi,

I just noticed a strange behavior that seems to be existing since 4.4.0. 4.3.4 works fine:

I build a service that runs two comparisions: one where the after step runs right after the before step (no issues), and one where the before step runs, then some software updates are triggered, and after the updates are finished (might take a few minutes), the after step is exectued. This works with 4.3.4, but since 4.4.0, the after step seems to not notice the before step. It just creates additional folders for the screenshots, instead of adding the after screenshots in the folders created by the before step, and the `report.json` only contains `screenshot-after-file-name` entries, `screenshot-before-file-name` is `null`.

**Comment by MediaMarco** [comment]
Hi Florian, would it be possible to get an example to reproduce the issue? Ideal would be an archive of the the report folder after the before step and the same one after both steps showing the strange behavior. It's hard to say how just a delay between both steps could be responsible for this. We use JLineup with delays of up to one hour between the steps.

**Comment by florianbrinkmann** [comment]
Hey Marco, yes, I will try to provide an example in the next days.

**Comment by MediaMarco** [comment]
Awesome! Thank you.

**Comment by florianbrinkmann** [comment]
Just as a follow-up: I did not forget that, but have currently no time to contiue work on my project, I will post the example here as soon as that changes again (might take another month).

**Comment by MediaMarco** [comment]
Hi @florianbrinkmann
I may have found the cause for this issue. Does any cookie change between before and after on your side?

**Comment by florianbrinkmann** [comment]
Hi @MediaMarco,
yes, I add two cookies to each jLineup run and for one comparision the values do not change, but for the second one (the failing one) the cookie values are different for before and after step.

**Comment by MediaMarco** [comment]
Hi @florianbrinkmann, Release 4.6.0 contains a bugfix for this, give it a try.

**Comment by florianbrinkmann** [comment]
Hi @MediaMarco, thanks a lot, it works! 🎉
