### ISSUE TITLE
report.json beinhaltet nicht das max-diff

### ISSUE THREAD

**Issue by dazasa** [otto-de/jlineup#3]
In der report.json fehlt momentan die Information ob ein Test fehlgeschlagen ist. Es wird zwar das difference ausgewiesen, dieses muss dann aber manuell wieder gegen das max-dif aus der lineup.json verglichen werden. Wäre es nicht Sinnvoll ein failure Status oder das max-diff auch in das report.json mit aufzunehmen?

Gruß
David

**Comment by MediaMarco** [comment]
Good idea!

**Comment by MediaMarco** [comment]
This is finally solved in 2.0.0.

There's a completely new report format with global max diff, diff sum, and the same for every url.
