### ISSUE TITLE
`device-config` needs to be `device` in docs

### ISSUE THREAD

**Issue by florianbrinkmann** [otto-de/jlineup#36]
First, thanks a lot for this tool!

I switched from the `window-widths` to device config recently and tried the `device-config` key like described in the docs (https://github.com/otto-de/jlineup/blob/master/docs/CONFIGURATION.md#device-config), but got an error for that. The key `device` worked.

**Comment by MediaMarco** [comment]
Thank you for your bug report! The correct key is `devices`. I fixed the documentation: https://github.com/otto-de/jlineup/blob/master/docs/CONFIGURATION.md#devices

**Comment by florianbrinkmann** [comment]
Oh yes, `devices`, you are right. Thanks for fixing it!
