### ISSUE TITLE
Create a readme.md file

### ISSUE THREAD

**Issue by rahulr892** [otto-de/jlineup#5]
Hi
Could you create a readme.md file to help with the start and using the jlineup tool and some tips as to how would you use it and also test scenarios where some page interaction is required to go to the desired page like login or click or something else ??

thanks ....

**Comment by MediaMarco** [comment]
I'll have to work on this! :smile:

**Comment by MediaMarco** [comment]
Hi again,

it took some time, but now the documentation is better! I'll close this issue.
